// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: proto/book_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_book_service_proto protoreflect.FileDescriptor

var file_proto_book_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x6f, 0x6f, 0x6b,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32,
	0xb9, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x54, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x20,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x61, 0x6c,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x74, 0x61, 0x6b, 0x65, 0x6e, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_proto_book_service_proto_goTypes = []interface{}{
	(*AuthorBooksRequest)(nil),  // 0: book_service.AuthorBooksRequest
	(*BookAuthorsRequest)(nil),  // 1: book_service.BookAuthorsRequest
	(*AuthorBooksResponse)(nil), // 2: book_service.AuthorBooksResponse
	(*BookAuthorsResponse)(nil), // 3: book_service.BookAuthorsResponse
}
var file_proto_book_service_proto_depIdxs = []int32{
	0, // 0: book_service.BookService.AuthorBooks:input_type -> book_service.AuthorBooksRequest
	1, // 1: book_service.BookService.BookAuthors:input_type -> book_service.BookAuthorsRequest
	2, // 2: book_service.BookService.AuthorBooks:output_type -> book_service.AuthorBooksResponse
	3, // 3: book_service.BookService.BookAuthors:output_type -> book_service.BookAuthorsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_book_service_proto_init() }
func file_proto_book_service_proto_init() {
	if File_proto_book_service_proto != nil {
		return
	}
	file_proto_transport_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_book_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_book_service_proto_goTypes,
		DependencyIndexes: file_proto_book_service_proto_depIdxs,
	}.Build()
	File_proto_book_service_proto = out.File
	file_proto_book_service_proto_rawDesc = nil
	file_proto_book_service_proto_goTypes = nil
	file_proto_book_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	AuthorBooks(ctx context.Context, in *AuthorBooksRequest, opts ...grpc.CallOption) (*AuthorBooksResponse, error)
	BookAuthors(ctx context.Context, in *BookAuthorsRequest, opts ...grpc.CallOption) (*BookAuthorsResponse, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) AuthorBooks(ctx context.Context, in *AuthorBooksRequest, opts ...grpc.CallOption) (*AuthorBooksResponse, error) {
	out := new(AuthorBooksResponse)
	err := c.cc.Invoke(ctx, "/book_service.BookService/AuthorBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) BookAuthors(ctx context.Context, in *BookAuthorsRequest, opts ...grpc.CallOption) (*BookAuthorsResponse, error) {
	out := new(BookAuthorsResponse)
	err := c.cc.Invoke(ctx, "/book_service.BookService/BookAuthors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	AuthorBooks(context.Context, *AuthorBooksRequest) (*AuthorBooksResponse, error)
	BookAuthors(context.Context, *BookAuthorsRequest) (*BookAuthorsResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) AuthorBooks(context.Context, *AuthorBooksRequest) (*AuthorBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorBooks not implemented")
}
func (*UnimplementedBookServiceServer) BookAuthors(context.Context, *BookAuthorsRequest) (*BookAuthorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookAuthors not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_AuthorBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).AuthorBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book_service.BookService/AuthorBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).AuthorBooks(ctx, req.(*AuthorBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_BookAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookAuthorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).BookAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book_service.BookService/BookAuthors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).BookAuthors(ctx, req.(*BookAuthorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book_service.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorBooks",
			Handler:    _BookService_AuthorBooks_Handler,
		},
		{
			MethodName: "BookAuthors",
			Handler:    _BookService_BookAuthors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/book_service.proto",
}
